namespace HakunaMatata.Data.DTOs
{
    public class FileDto
    {
        public Stream Content { get; set; }
        public string Name { get; set; }
        public string ContentType { get; set; }

        public string GetPathWithFileName()
        {
            var uniqueAutoGeneratedFileName = Path.GetRandomFileName();
            var shortClientSideFileNameWithoutExt = Path.GetFileNameWithoutExtension(Name);

            if (shortClientSideFileNameWithoutExt.Length > 10)
                shortClientSideFileNameWithoutExt = shortClientSideFileNameWithoutExt.Substring(0, 10);
            
            var ext = Path.GetExtension(Name);
            var basePath = "images/";

            return basePath + uniqueAutoGeneratedFileName + "_" + shortClientSideFileNameWithoutExt + ext;
        }
    }
}
